<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- ROBOT DIMENSIONS -->
    <!-- Drive wheels and ZED camera are at the front (+X) -->
    <!-- Caster wheel is at the rear (-X) -->
    <xacro:property name="base_length" value="0.6096" />      <!-- 24 inches -->
    <xacro:property name="base_width" value="0.3048" />       <!-- 12 inches -->
    <xacro:property name="base_height" value="0.0635" />      <!-- 2.5 inches -->
    <xacro:property name="base_mass" value="6.8" />           <!-- ~15 lbs -->

    <xacro:property name="wheel_radius" value="0.04756" />    <!-- 95.11mm diameter -->
    <xacro:property name="wheel_length" value="0.03195" />    <!-- 31.95mm width -->
    <xacro:property name="wheel_mass" value="0.5" />          <!-- kg estimate -->
    <xacro:property name="wheel_separation" value="0.42285" /> <!-- 422.85mm center-to-center -->

    <!-- Wheel X position - near front edge of chassis -->
    <xacro:property name="wheel_x_offset" value="${base_length / 2.0 - 0.06}" />

    <!-- BASE FOOTPRINT -->
    <link name="base_footprint" />

    <!-- BASE LINK -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <inertial>
            <mass value="${base_mass}" />
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <inertia ixx="${(1/12) * base_mass * (base_width*base_width + base_height*base_height)}"
                     ixy="0" ixz="0"
                     iyy="${(1/12) * base_mass * (base_length*base_length + base_height*base_height)}"
                     iyz="0"
                     izz="${(1/12) * base_mass * (base_length*base_length + base_width*base_width)}" />
        </inertial>
    </link>

    <!-- WHEEL MACRO -->
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <inertial>
                <mass value="${wheel_mass}" />
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_length*wheel_length)}"
                         ixy="0" ixz="0"
                         iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_length*wheel_length)}"
                         iyz="0"
                         izz="${(1/2) * wheel_mass * wheel_radius*wheel_radius}" />
            </inertial>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />

    <!-- CASTER WHEEL -->
    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <inertial>
            <mass value="0.2" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
        </inertial>
    </link>

    <!-- IMU LINK -->
    <link name="imu_link">
        <visual>
            <geometry>
                <box size="0.03 0.03 0.01" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="green">
                <color rgba="0 1 0 1" />
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.03 0.03 0.01" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01" />
            <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001" />
        </inertial>
    </link>

    <!-- ZED2i CAMERA LINK -->
    <!-- Named 'zed_camera_link' to match the ZED wrapper's TF frame,
         connecting the robot URDF tree to the ZED's internal frame chain -->
    <link name="zed_camera_link">
        <visual>
            <geometry>
                <box size="0.033 0.175 0.030" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="dark_grey">
                <color rgba="0.2 0.2 0.2 1" />
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.033 0.175 0.030" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.175" />
            <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001" />
        </inertial>
    </link>

    <!-- JOINTS -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <!-- Drive wheels at rear but changed to front -->
    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${wheel_x_offset} ${-wheel_separation / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${wheel_x_offset} ${wheel_separation / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <!-- Caster at the front, but we consider it rear -->
    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${-wheel_x_offset} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" />
    </joint>

    <!-- IMU centered on top of chassis not quite right, doesn't really matter, can add meshes later -->
    <joint name="imu_joint" type="fixed">
        <parent link="base_link" />
        <child link="imu_link" />
        <origin xyz="0 0 ${base_height + 0.005}" rpy="0 0 0" />
    </joint>

    <!-- ZED camera at front edge, on top of chassis, facing forward (rear) -->
    <joint name="camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="zed_camera_link" />
        <origin xyz="${base_length / 2.0 - 0.02} 0 ${base_height + 0.015}" rpy="0 0 0" />
    </joint>

</robot>